[server]
# Set max upload size to 1GB (1000 MB)
maxUploadSize = 1000

[browser]
# Disable usage stats
gatherUsageStats = false

[theme]
# Light theme configuration
base = "light"
primaryColor = "#ad1d6a"
backgroundColor = "#f6f9ff"
secondaryBackgroundColor = "#eef3fb"
textColor = "#14213d"
font = "sans serif"
